### ISSUE TITLE
CodecType的getCodec方法获取的codec对象为空

### ISSUE THREAD

**Issue by bcsixxyx** [fartherp/shiro-redisson#2]
CodecType的getCodec方法获取的codec对象为空，可能时反射工具的问题
redisson版本号3.7.0

**Comment by fartherp** [comment]
3.7.0默认的编码还不是fst，需要引入以下包才可以，或者升级版本
        <dependency>
            <groupId>de.ruedigermoeller</groupId>
            <artifactId>fst</artifactId>
            <version>2.54</version>
        </dependency>

**Comment by fartherp** [comment]
编码不存在时，默认编码改成json
