### ISSUE TITLE
通过sessionid从redis中获取session为空, 引起空指针异常

### ISSUE THREAD

**Issue by Carl-Yang** [fartherp/shiro-redisson#4]
com.github.fartherp.shiro.RedisSessionDAO的122行获取到session为空, 后面没做非空校验,导致124方法执行时抛出空指针异常

**Comment by fartherp** [comment]
1.1.3正式版本中解决，目前1.1.3-SNAPSHOT版本已解决

**Comment by fartherp** [comment]
1.1.3版本已发布
